name: Deploy to Cozycabs Prod Server

on:
  push:
    branches:
      - prod

env:
  AWS_REGION: ap-south-1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Configure Service
      run: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
        sudo apt install -y nodejs
        npm i
        npm run build 
        mv src/keys dist/keys
        mv src/views dist/views

    - name: Copy code to EC2 instance
      uses: appleboy/scp-action@master
      with:
        host: 13.200.162.71
        username: "ubuntu"
        key_path: ./.github/prod.pem
        source: .
        target: /DATA01/builds/cozycabs-server-new/

    - name: Restart Service
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: "13.200.162.71"
        username: "ubuntu"
        key_path: ./.github/prod.pem
        port: 22
        script: |
          rm -rf /DATA01/builds/cozycabs-server-old
          mv /DATA01/builds/cozycabs-server /DATA01/builds/cozycabs-server-old
          mv /DATA01/builds/cozycabs-server-new /DATA01/builds/cozycabs-server
          cd /DATA01/builds/cozycabs-server 
          pm2 reload cozycabs_server